# Generated by Django 4.2.7 on 2024-01-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_like_question_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_for_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Like_for_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='question',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='correct_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='count_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='count_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='count_of_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='count_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='app.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.AddField(
            model_name='like_for_question',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_for_ques', to='app.question'),
        ),
        migrations.AddField(
            model_name='like_for_question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
        migrations.AddField(
            model_name='like_for_answer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_for_ans', to='app.answer'),
        ),
        migrations.AddField(
            model_name='like_for_answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
    ]
