# Generated by Django 4.2.7 on 2024-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like_for_answer',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='like_for_question',
            old_name='user',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='like_for_answer',
            name='value',
            field=models.IntegerField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='like_for_question',
            name='value',
            field=models.IntegerField(blank=True, max_length=2),
        ),
    ]
